language: d

os: linux
dist: xenial

d:
  - dmd
  - ldc

addons:
  apt:
    update: true
    sources:
      - deadsnakes
    packages:
      # dependencies for meson
      - python3.6
      - python3.6-pip
      - python3.6-setuptools
      - python3.6-wheel

install:
  - pip3 install meson ninja

script:
  - meson setup builddir
  - meson compile -C builddir
  - meson test -C builddir
