language: d

dist: xenial

d:
  - dmd
  - ldc

sudo: required

addons:
  apt:
    update: true
    sources:
      - deadsnakes
      - sourceline: 'ppa:ubuntu-toolchain-r/test'
      - sourceline: 'deb https://packagecloud.io/chef/stable/ubuntu/precise main'
        key_url: 'https://packagecloud.io/gpg.key'
    packages:
      - gcc-8
      # dependencies for meson
      - python3
      - python3-pip
      - python3-setuptools
      - python3-wheel

install:
  - pip3 install meson ninja

script:
  - meson setup builddir
  - meson compile -C builddir
  - meson test -C builddir
