language: d

os: linux
dist: xenial

d:
  - dmd
  - ldc

addons:
  apt:
    update: true
    sources:
      - deadsnakes
    packages:
      - lua5.3
      - lua5.3-dev
      # dependencies for meson
      - python3.6
      - python3.6-dev
      - python3.6-venv
      - python3-pip
      - python3-setuptools
      - python3-wheel

install:
  - python3.6 -m pip install meson ninja
  - rdmd tools/meson-dub-deps.d --dc $DC

script:
  - meson setup builddir
  - meson compile -C builddir
  - meson test -v
