language: d

dist: focal

d:
  - dmd
  - ldc

before_install:
  - pyenv

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - deadsnakes
    packages:
      # dependencies for meson
      - python3
      - python3-pip
      - python3-setuptools
      - python3-wheel

install:
  - pip3 install meson ninja

script:
  - meson setup builddir
  - meson compile -C builddir
  - meson test -C builddir
