name: dopamine

services:
  database:
    image: postgres
    volumes:
      - type: volume
        source: db-data
        target: /var/lib/postgresql/data
    ports:
      # on host, the database available at
      # postgres://dopreg:dopreg@localhost:6543/dop-registry
      # psql -U dopreg -h localhost -p 6543 -d dop-registry
      # dop-admin must be run first with --create-user and --create-db
      - 6543:5432
    environment:
      - POSTGRES_PASSWORD=postgres

  # client applications: dop and dop-admin
  client:
    depends_on:
      # we specify the database and not the registry on purpose
      # client can run without registry for some commands
      # we start the database so that dop-admin connects to it
      - database
    build:
      context: ${dopdir}
      dockerfile: ${dopdir}/docker/client.dockerfile
    volumes:
      - type: volume
        source: client-home
        target: /home/me
    environment:
      - DOP_REGISTRY=http://registry
      - DOP_ADMIN_CONNSTRING=postgres://postgres:postgres@database/postgres
      - DOP_DB_CONNSTRING=postgres://dopreg:dopreg@database/dop-registry

  registry:
    depends_on:
      - database
    build:
      context: ${dopdir}
      dockerfile: ${dopdir}/docker/registry.dockerfile
    volumes:
      - type: volume
        source: registry-storage
        target: /storage
    ports:
      - 3500:80
    environment:
      - DOP_REGISTRY_HOSTNAME=0.0.0.0
      - DOP_REGISTRY_PORT=80
      - DOP_DB_CONNSTRING=postgres://dopreg:dopreg@database/dop-registry
      - DOP_REGISTRY_STORAGEDIR=/storage
    env_file:
      - ${dopdir}/packages/registry/.env.dev

  frontend:
    depends_on:
      - registry
    build:
      context: ${dopdir}/web
      dockerfile: ${dopdir}/docker/frontend-dev.dockerfile
      args:
        - web_api_host=http://localhost:3500
        - web_github_clientid=${web_github_clientid}
        - web_google_clientid=${web_google_clientid}
    volumes:
      - ${dopdir}/web/src:/app/src
      - ${dopdir}/web/public:/app/public
    ports:
      - 3000:3000

volumes:
  db-data:
  client-home:
  registry-storage:
