services:
  registry:
    image: ${registry_img}
    build:
      context: ${dopdir}
      dockerfile: ${dopdir}/docker/registry.dockerfile
      args:
        - "build_type=${build_type}"
        - "dc=${dc}"
        - "web_api_host=${web_api_host}"
        - "web_api_prefix=${web_api_prefix}"
        - "web_github_clientid=${web_github_clientid}"
        - "web_google_clientid=${web_google_clientid}"
    ports:
      - ${port_map}
    env_file: ${env_file}
