name: CI

on: [push, pull_request]

jobs:
  test:
    name: Installation and tests

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        dc: [dmd-latest, ldc-latest]
        meson: ['0.62.0']

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: D Compiler Installation
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.dc }}

      - name: Install Meson Linux
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo python -m pip install ninja meson==${{ matrix.meson }}

      - name: Install Meson Windows
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          python -m pip install ninja meson==${{ matrix.meson }}

      - name: Enable MS Developer Command Prompt
        if: ${{ matrix.os == 'windows-latest' }}
        uses: ilammy/msvc-dev-cmd@v1.7.0

      - name: Build dopamine
        run: |
          meson setup build -Ddefault_library=static
          meson compile -C build

      - name: Run dopamine tests
        run: meson test --print-errorlogs
        working-directory: build
