name: CI

on: [push, pull_request]

jobs:
  test:
    name: Installation and tests

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        dc: [dmd-latest, ldc-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: D Compiler Installation
        uses: dlang-community/setup-dlang@v1.0.6
        with:
          compiler: ${{ matrix.dc }}

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install Lua
        uses: xpol/setup-lua@v0.2
        with:
          luaVersion: "5.3"

      - name: Install Dub dependencies
        run: rdmd tools/meson_dub_deps.d --dc $DC

      - name: Build dopamine
        uses: BSFishy/meson-build@v1.0.2
        with:
          action: build
          directory: build
          meson-version: 0.57.1
          setup-options: -Ddefault_library=static -Dlua_bindings=dynamic -Dlua_version=53

      - name: Run tests
        run: lib/doptest -t 1
        working-directory: build
