name: CI

on: [push, pull_request]

jobs:
  test:
    name: Installation and tests

    strategy:
      matrix:
        # os: [ubuntu-latest, windows-latest]
        # dc: [dmd-latest, ldc-latest]
        os: [windows-latest]
        dc: [dmd-latest]
        lua: ['5.3.6']
        # lua: ['5.1.5', '5.2.4', '5.3.6']

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: D Compiler Installation
        uses: dlang-community/setup-dlang@v1.0.6
        with:
          compiler: ${{ matrix.dc }}

      - name: Install Lua Linux
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: sudo apt-get install lua5.3 liblua5.3-dev

      - name: Install Lua Windows
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          curl -L "http://downloads.sourceforge.net/project/luabinaries/${{ matrix.lua }}/Tools Executables/lua-${{ matrix.lua }}_Win64_bin.zip" -o lua.zip
          7z x lua.zip -olua
          echo "$PWD\lua" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Install Dub dependencies
        run: rdmd tools/meson_dub_deps.d --dc ${{ env.DC }}

      - run: echo "$HOME/.local/bin" >> $GITHUB_PATH
        if: ${{ matrix.os == 'ubuntu-latest' }}

      - name: Build dopamine
        uses: BSFishy/meson-build@v1.0.2
        with:
          action: build
          directory: build
          meson-version: 0.57.1
          setup-options: -Ddefault_library=static -Dlua_bindings=dynamic -Dlua_version=53

      - name: Run tests
        run: |
          lib/doptest -t 1
        working-directory: build

