name: CI

on: [push, pull_request]

jobs:
  test:
    name: Installation and tests

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        dc: [dmd-latest, ldc-latest]
        meson: ['0.57.1']

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: D Compiler Installation
        uses: dlang-community/setup-dlang@v1.0.6
        with:
          compiler: ${{ matrix.dc }}

      - name: Install Meson Linux
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo python -m pip install meson==${{ matrix.meson }}
          sudo python -m pip install ninja

      - name: Install Meson Windows
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          python -m pip install meson==${{ matrix.meson }}
          python -m pip install ninja
        shell: bash

      - name: Install Dub dependencies
        run: rdmd tools/meson_dub_deps.d --dc ${{ env.DC }}

      - name: Build dopamine
        run: |
          meson setup build -Ddefault_library=static
          meson compile -C build
        shell: bash

      - name: Run dopamine tests
        run: lib/doptest -t 1 -v
        working-directory: build
        shell: bash
